/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/session': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Session */
    get: operations['get_session_api_v1_session_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/games': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Games */
    get: operations['list_games_api_v1_games_get']
    put?: never
    /** Create Game */
    post: operations['create_game_api_v1_games_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/games/{game_id}/start': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start Game */
    post: operations['start_game_api_v1_games__game_id__start_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/games/{game_id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Cancel Game */
    post: operations['cancel_game_api_v1_games__game_id__cancel_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/games/{game_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Game */
    get: operations['get_game_api_v1_games__game_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/games/{game_id}/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Events */
    get: operations['list_events_api_v1_games__game_id__events_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/games/{game_id}/review': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Game Review */
    get: operations['get_game_review_api_v1_games__game_id__review_get']
    put?: never
    /** Create Game Review */
    post: operations['create_game_review_api_v1_games__game_id__review_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/games/{game_id}/stream': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Stream Events */
    get: operations['stream_events_api_v1_games__game_id__stream_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health/live': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Live */
    get: operations['live_health_live_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Ready */
    get: operations['ready_health_ready_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** CreateGameRequest */
    CreateGameRequest: {
      /** Player Count */
      player_count: number
    }
    /** DayVotePayload */
    DayVotePayload: {
      /** Player */
      player: string
      /** Vote */
      vote: string
      /** Reason */
      reason: string
      /** Suspicion Level */
      suspicion_level: number
    } & {
      [key: string]: unknown
    }
    /** DiscussionStartedPayload */
    DiscussionStartedPayload: {
      /** Discussion Kind */
      discussion_kind: string
      /** Round */
      round: number
      /** Participants */
      participants: string[]
    } & {
      [key: string]: unknown
    }
    /** ErrorPayload */
    ErrorPayload: {
      /** Error Code */
      error_code?: string | null
    } & {
      [key: string]: unknown
    }
    /** EventResponse */
    EventResponse: {
      /** Game Id */
      game_id: string
      /** Seq */
      seq: number
      /**
       * Type
       * @enum {string}
       */
      type:
        | 'identity_assigned'
        | 'game_started'
        | 'night_started'
        | 'day_started'
        | 'discussion_started'
        | 'speaker_turn_started'
        | 'speech'
        | 'speech_moderated'
        | 'werewolf_vote'
        | 'seer_result'
        | 'witch_action'
        | 'day_vote'
        | 'hunter_action'
        | 'night_result'
        | 'vote_result'
        | 'roles_revealed'
        | 'game_finished'
        | 'game_cancelled'
        | 'game_interrupted'
        | 'game_failed'
      /**
       * Phase
       * @enum {string}
       */
      phase: 'setup' | 'night' | 'day' | 'finished'
      /**
       * Visibility
       * @enum {string}
       */
      visibility: 'public' | 'private' | 'internal'
      /** Recipients */
      recipients: string[]
      /** Payload */
      payload:
        | components['schemas']['IdentityPayload']
        | components['schemas']['GameStartedPayload']
        | components['schemas']['PhaseStartedPayload']
        | components['schemas']['DiscussionStartedPayload']
        | components['schemas']['SpeakerPayload']
        | components['schemas']['SpeechPayload']
        | components['schemas']['ModeratedSpeechPayload']
        | components['schemas']['WerewolfVotePayload']
        | components['schemas']['SeerResultPayload']
        | components['schemas']['WitchActionPayload']
        | components['schemas']['DayVotePayload']
        | components['schemas']['HunterActionPayload']
        | components['schemas']['NightResultPayload']
        | components['schemas']['VoteResultPayload']
        | components['schemas']['RolesRevealedPayload']
        | components['schemas']['FinishedPayload']
        | components['schemas']['ErrorPayload']
        | {
            [key: string]: unknown
          }
      /** Created At */
      created_at: string
    }
    /** FinishedPayload */
    FinishedPayload: {
      /** Winner */
      winner: string
    } & {
      [key: string]: unknown
    }
    /** GameResponse */
    GameResponse: {
      /** Id */
      id: string
      /** Player Count */
      player_count: number
      /**
       * Status
       * @enum {string}
       */
      status: 'created' | 'running' | 'completed' | 'draw' | 'cancelled' | 'interrupted' | 'failed'
      /**
       * Phase
       * @enum {string}
       */
      phase: 'setup' | 'night' | 'day' | 'finished'
      /** Round Number */
      round_number: number
      /** Players */
      players: components['schemas']['PlayerResponse'][]
      /** Winner */
      winner?: string | null
      /** Error Code */
      error_code?: string | null
      /** Created At */
      created_at: string
      /** Started At */
      started_at?: string | null
      /** Finished At */
      finished_at?: string | null
    }
    /** GameReviewResponse */
    GameReviewResponse: {
      /** Game Id */
      game_id: string
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'completed' | 'failed'
      result?: components['schemas']['GameReviewResult'] | null
      /** Error Code */
      error_code?: string | null
      /** Created At */
      created_at: string
      /** Completed At */
      completed_at?: string | null
    }
    /** GameReviewResult */
    GameReviewResult: {
      /** Title */
      title: string
      /** Overview */
      overview: string
      /** Turning Points */
      turning_points: components['schemas']['TurningPoint'][]
      /** Winning Factors */
      winning_factors: string[]
      /** Player Reviews */
      player_reviews: components['schemas']['PlayerReview'][]
      /** Mvp */
      mvp: string
      /** Closing Comment */
      closing_comment: string
    }
    /** GameStartedPayload */
    GameStartedPayload: {
      /** Players */
      players: string[]
    } & {
      [key: string]: unknown
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HunterActionPayload */
    HunterActionPayload: {
      /** Player */
      player: string
      /** Shoot */
      shoot: boolean
      /** Target */
      target?: string | null
      /** Shoot Reason */
      shoot_reason?: string | null
    } & {
      [key: string]: unknown
    }
    /** IdentityPayload */
    IdentityPayload: {
      /** Player */
      player: string
      /** Role */
      role: string
    } & {
      [key: string]: unknown
    }
    /** ModeratedSpeechPayload */
    ModeratedSpeechPayload: {
      /** Player */
      player: string
      /**
       * Status
       * @enum {string}
       */
      status: 'blocked' | 'unavailable'
      /** Categories */
      categories: string[]
    } & {
      [key: string]: unknown
    }
    /** NightResultPayload */
    NightResultPayload: {
      /** Deaths */
      deaths: string[]
    } & {
      [key: string]: unknown
    }
    /** PhaseStartedPayload */
    PhaseStartedPayload: {
      /** Round */
      round: number
    } & {
      [key: string]: unknown
    }
    /** PlayerResponse */
    PlayerResponse: {
      /** Name */
      name: string
      /** Character */
      character: string
      /** Is Alive */
      is_alive: boolean
      /** Role */
      role?: string | null
      /** Has Antidote */
      has_antidote?: boolean | null
      /** Has Poison */
      has_poison?: boolean | null
      /** Persona Tags */
      persona_tags?: string[]
    }
    /** PlayerReview */
    PlayerReview: {
      /** Player */
      player: string
      /** Character */
      character: string
      /** Role */
      role: string
      /** Score */
      score: number
      /** Role Completion */
      role_completion: string
      /** Highlights */
      highlights?: string[]
      /** Mistakes */
      mistakes?: string[]
      /** Evidence Event Seqs */
      evidence_event_seqs: number[]
    }
    /** RevealedRole */
    RevealedRole: {
      /** Player */
      player: string
      /** Role */
      role: string
    }
    /** RolesRevealedPayload */
    RolesRevealedPayload: {
      /** Players */
      players: components['schemas']['RevealedRole'][]
    } & {
      [key: string]: unknown
    }
    /** SeerResultPayload */
    SeerResultPayload: {
      /** Target */
      target: string
      /** Is Werewolf */
      is_werewolf: boolean
    } & {
      [key: string]: unknown
    }
    /** SessionResponse */
    SessionResponse: {
      /**
       * Authenticated
       * @default true
       * @constant
       */
      authenticated: true
      /** Capabilities */
      capabilities: ('control' | 'public_view' | 'god_view')[]
    }
    /** SpeakerPayload */
    SpeakerPayload: {
      /** Player */
      player: string
      /** Round */
      round: number
      /** Discussion Round */
      discussion_round: number
      /** Discussion Kind */
      discussion_kind: string
    } & {
      [key: string]: unknown
    }
    /** SpeechPayload */
    SpeechPayload: {
      /** Player */
      player: string
      /** Round */
      round: number
      /** Discussion Round */
      discussion_round: number
      /** Discussion Kind */
      discussion_kind: string
      /** Content */
      content: string
    } & {
      [key: string]: unknown
    }
    /** TurningPoint */
    TurningPoint: {
      /** Title */
      title: string
      /** Analysis */
      analysis: string
      /** Event Seqs */
      event_seqs: number[]
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /** VoteResultPayload */
    VoteResultPayload: {
      /** Voted Out */
      voted_out: string | null
      /** Votes */
      votes: number
      /** Hunter Shot */
      hunter_shot: string | null
    } & {
      [key: string]: unknown
    }
    /** WerewolfVotePayload */
    WerewolfVotePayload: {
      /** Player */
      player: string
      /** Target */
      target: string
      /** Kill Strategy */
      kill_strategy: string
      /** Team Coordination */
      team_coordination?: string | null
    } & {
      [key: string]: unknown
    }
    /** WitchActionPayload */
    WitchActionPayload: {
      /** Player */
      player: string
      /** Action */
      action: string
      /** Target Name */
      target_name?: string | null
      /** Action Reason */
      action_reason?: string | null
    } & {
      [key: string]: unknown
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_session_api_v1_session_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionResponse']
        }
      }
    }
  }
  list_games_api_v1_games_get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_game_api_v1_games_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateGameRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_game_api_v1_games__game_id__start_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        game_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  cancel_game_api_v1_games__game_id__cancel_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        game_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_game_api_v1_games__game_id__get: {
    parameters: {
      query?: {
        view?: 'public' | 'god'
      }
      header?: never
      path: {
        game_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_events_api_v1_games__game_id__events_get: {
    parameters: {
      query?: {
        after_seq?: number
        view?: 'public' | 'god'
      }
      header?: never
      path: {
        game_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EventResponse'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_game_review_api_v1_games__game_id__review_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        game_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameReviewResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_game_review_api_v1_games__game_id__review_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        game_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GameReviewResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  stream_events_api_v1_games__game_id__stream_get: {
    parameters: {
      query?: {
        view?: 'public' | 'god'
      }
      header?: {
        'Last-Event-ID'?: string | null
      }
      path: {
        game_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  live_health_live_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
  ready_health_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
}
